name: Cypress API Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install Packages
        run:  npm install  
      - name: npx cypress run --env allure=true
        uses: cypress-io/github-action@v2
        with:
          start: npm start
      - name: Generate Allure Report
        run: npm run allure generate allure-results --clean -o allure-report

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
